# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.1
_src_path: gh:radio-aktywne/template-app-next
accountname: radio-aktywne
appname: webshows
description: Emission shows web UI 🎭
docs: true
docsurl: https://radio-aktywne.github.io/app-webshows
envprefix: WEBSHOWS
imagename: apps/webshows
keyprefix: webshows
port: 37000
registry: true
releases: true
reponame: app-webshows
repourl: https://github.com/radio-aktywne/app-webshows
