services:
  webshows:
    build:
      context: ./
      network: host
    environment:
      - "WEBSHOWS__SERVER__HOST=${WEBSHOWS__SERVER__HOST:-0.0.0.0}"
      - "WEBSHOWS__SERVER__PORT=${WEBSHOWS__SERVER__PORT:-37000}"
      - "WEBSHOWS__EMISHOWS__SCHEME=${WEBSHOWS__EMISHOWS__SCHEME:-http}"
      - "WEBSHOWS__EMISHOWS__HOST=${WEBSHOWS__EMISHOWS__HOST:-localhost}"
      - "WEBSHOWS__EMISHOWS__PORT=${WEBSHOWS__EMISHOWS__PORT:-35000}"
      - "WEBSHOWS__EMISHOWS__PATH=${WEBSHOWS__EMISHOWS__PATH:-}"
    network_mode: host
